language: python

python: 
  - "3.5"
  - "3.6"

cache: pip

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - coverage run  --source app/tests/v1 -m pytest -v

after_success:
  - coveralls
  - codecov --token=093aeaa3-4bb6-4d14-a60c-ae41278f9254



  